const KONGLISH = (k) => `한국에서 쓰는 '${k}'에 해당하는 자연스러운 영어 표현은?`
const eun = (w) => ((w.slice(-1).charCodeAt(0) - 0xac00) % 28 ? '은' : '는')
const ORIGIN = (w) => `'${w}'${eun(w)} 어느 나라 말에서 왔을까?`

export default {
  category: 'loanword',
  name: 'm',
  label: '외래어',
  cards: [
    // ── 외래어 뜻: 쉬움 ──
    { a: '트렌드', d: 'e', m: '사회의 흐름이나 유행의 방향', t: 'trend = 경향' },
    { a: '슬럼프', d: 'e', m: '실력이나 의욕이 일시적으로 떨어지는 부진한 시기', t: 'slump = 털썩 주저앉다' },
    { a: '징크스', d: 'e', m: '불길하게 여겨지는 일이나 늘 되풀이되는 나쁜 운', t: '빨간 펜으로 이름 쓰면 안 된다는 식의 믿음' },
    { a: '루틴', d: 'e', m: '규칙적으로 반복하는 일의 순서나 습관', t: '아침 루틴: 물 한 잔 → 스트레칭' },
    { a: '스포일러', d: 'e', b: 'spoil=망치다', m: '영화나 책의 내용을 미리 알려 재미를 떨어뜨리는 것', t: '"범인은 ○○○야" = 스포' },
    { a: '컬래버레이션', d: 'e', b: 'co=함께 / labor=일하다', m: '둘 이상의 사람이나 브랜드가 함께 작업하는 것', t: '줄여서 콜라보, 협업' },
    { a: '번아웃', d: 'e', b: 'burn out=다 타 버리다', m: '지나친 업무나 스트레스로 몸과 마음이 탈진한 상태', t: '다 타 버린 양초' },
    { a: '멘토', d: 'e', m: '경험과 지혜로 다른 사람을 이끌어 주는 조언자', x: '그리스 신화에서 오디세우스가 아들의 교육을 맡긴 친구 \'멘토르\'에서 나왔어요.', t: '멘토 ↔ 멘티' },
    { a: '피드백', d: 'e', b: 'feed=주다 / back=되돌려', m: '어떤 일의 결과에 대한 의견이나 반응을 되돌려 주는 것', t: '"피드백 부탁드려요"' },
    { a: '매뉴얼', d: 'e', b: 'manual=손(manus)으로 하는', m: '일의 순서나 사용 방법을 정리한 안내서', t: '설명서 = 매뉴얼' },
    { a: '해프닝', d: 'e', b: 'happen=일어나다', m: '우연히 일어난 뜻밖의 작은 사건', t: '웃고 넘길 만한 소동' },
    { a: '로망', d: 'e', b: 'roman=프랑스어로 소설', m: '마음속으로 꿈꾸고 바라는 것', t: '바닷가 카페 차리기가 내 로망' },
    { a: '오리엔테이션', d: 'e', b: 'orient=동쪽, 방향을 잡다', m: '새로운 환경에 적응하도록 미리 안내하는 교육', t: '새내기 OT' },

    // ── 외래어 뜻: 보통 ──
    { a: '노스탤지어', d: 'n', b: 'nostos=귀향(그리스어) / algos=고통(그리스어)', l: '돌아가고 싶은 아픔', m: '고향이나 지나간 시절을 그리워하는 마음', t: '옛날 노래 들으면 드는 그 감정' },
    { a: '아이러니', d: 'n', m: '겉으로 드러난 것과 실제가 반대되는 상황이나 표현', t: '소방서에 불이 남' },
    { a: '딜레마', d: 'n', b: 'di=둘(그리스어) / lemma=전제', m: '둘 중 하나를 골라야 하는데 어느 쪽도 곤란한 상황', t: '진퇴양난의 외래어 버전' },
    { a: '패러디', d: 'n', m: '잘 알려진 작품을 흉내 내어 풍자하거나 재미있게 바꾼 것', t: '명화 따라 하기 사진', syn: ['오마주'] },
    { a: '오마주', d: 'n', b: 'hommage=프랑스어로 존경', m: '존경의 뜻으로 다른 작가의 작품 일부를 따라 하는 것', t: '감독이 존경하는 거장의 장면 재현' },
    { a: '클리셰', d: 'n', b: 'cliché=프랑스어로 판에 박힌 인쇄판', m: '너무 자주 써서 진부해진 표현이나 설정', t: '재벌 2세와 가난한 주인공' },
    { a: '시너지', d: 'n', b: 'syn=함께 / ergon=일(그리스어)', m: '둘 이상이 합쳐져 따로일 때보다 더 큰 효과를 내는 것', t: '1 + 1 = 3' },
    { a: '매너리즘', d: 'n', m: '늘 같은 방식을 되풀이해 신선함과 독창성을 잃는 것', t: '매일 똑같은 일상에 지침', x: '르네상스 이후 대가들의 방식(manner)만 흉내 낸 미술 경향에서 나온 말이에요.' },
    { a: '마지노선', d: 'n', m: '더는 물러설 수 없는 마지막 한계선', t: '"이 가격이 마지노선이에요"', x: '제2차 세계 대전 전 프랑스가 독일 국경에 쌓은 요새선의 이름(국방장관 마지노)에서 나왔어요. 독일군은 이 선을 우회해 프랑스를 점령했어요.' },
    { a: '카리스마', d: 'n', b: 'charisma=그리스어로 신의 은총', m: '다른 사람들이 따르게 만드는 강한 매력이나 지도력', t: '눈빛만으로 압도' },
    { a: '패러다임', d: 'n', b: 'paradeigma=그리스어로 본보기', m: '한 시대 사람들의 생각을 지배하는 사고의 틀', t: '스마트폰이 바꾼 생활 패러다임', x: '과학사학자 토머스 쿤이 널리 쓰이게 만든 말이에요.' },
    { a: '레퍼토리', d: 'n', m: '공연자가 언제든 할 수 있도록 준비해 둔 작품 목록, 또는 늘 하는 이야기', t: '아빠의 군대 이야기 레퍼토리' },
    { a: '앙상블', d: 'n', b: 'ensemble=프랑스어로 함께', m: '여러 요소가 조화를 이룸, 또는 소규모 합주단', t: '배우들의 연기 앙상블' },
    { a: '팬데믹', d: 'n', b: 'pan=모든(그리스어) / demos=사람들', m: '전염병이 전 세계적으로 크게 유행하는 상태', t: '모든 사람에게 퍼진 병' },
    { a: '프레임', d: 'n', b: 'frame=틀', m: '어떤 문제를 바라보고 해석하는 틀', t: '"프레임을 씌우다"' },
    { a: '가스라이팅', d: 'n', m: '상황을 교묘히 조작해 상대가 스스로를 의심하게 만들어 지배하는 것', t: '"네가 예민한 거야"를 반복', x: '아내를 미치게 만들려고 가스등을 몰래 조작하는 남편이 나오는 영화 「가스등」에서 나왔어요.' },
    { a: '캐리커처', d: 'n', b: 'caricare=이탈리아어로 과장하다', m: '사람의 특징을 과장해 우스꽝스럽게 그린 그림', t: '큰 코를 더 크게' },
    { a: '다크호스', d: 'n', b: 'dark horse=정체를 모르는 말(馬)', m: '예상하지 못한 뛰어난 실력을 보일 수 있는 인물', t: '경마에서 정보가 없던 말이 우승한 데서 나왔어요' },
    { a: '뉘앙스', d: 'n', m: '말이나 표현에 담긴 미묘한 차이나 느낌', t: '"괜찮아"와 "괜찮아..."의 차이' },
    { a: '니즈', d: 'n', b: 'needs=필요', m: '소비자가 바라는 필요나 요구', t: '"고객 니즈를 파악하라"' },
    { a: '포트폴리오', d: 'n', b: 'portfolio=서류 가방', m: '자기 작품이나 경력을 모은 자료, 또는 여러 자산에 나눠 투자한 구성', t: '디자이너의 작품집, 투자자의 분산 투자' },
    { a: '미션', d: 'n', b: 'mission=보내다(라틴어 mittere)', m: '맡겨진 임무', t: '"미션 클리어!"' },
    { a: '에피소드', d: 'n', m: '이야기 중간에 끼어든 짧은 이야기나 재미있는 일화', t: '드라마 1화 = 에피소드 1' },

    // ── 외래어 뜻: 어려움 ──
    { a: '아우라', d: 'h', b: 'aura=그리스어로 숨결, 미풍', m: '사람이나 예술 작품에서 풍기는 독특하고 신비로운 분위기', t: '범접할 수 없는 분위기' },
    { a: '헤게모니', d: 'h', b: 'hegemonia=그리스어로 지도, 우두머리', m: '한 집단이 다른 집단을 이끌고 지배하는 주도권', t: '"헤게모니 싸움"' },
    { a: '아이콘', d: 'h', b: 'eikon=그리스어로 형상, 모습', m: '어떤 분야나 시대를 대표하는 상징적인 인물이나 사물', t: '패션 아이콘' },
    { a: '컨센서스', d: 'h', b: 'con=함께 / sentire=느끼다(라틴어)', m: '여러 사람의 의견이 일치하는 것', t: '"시장 컨센서스(전망치)"' },
    { a: '플라세보 효과', d: 'h', b: 'placebo=라틴어로 나는 기쁘게 하리라', m: '가짜 약이라도 효과가 있다고 믿으면 실제로 증상이 나아지는 현상', t: '밀가루 약도 믿으면 효과', x: '반대로 해롭다고 믿어서 실제로 나빠지는 현상은 \'노세보 효과\'예요.' },
    { a: '노블레스 오블리주', d: 'h', b: 'noblesse=귀족 / oblige=의무를 지우다(프랑스어)', m: '높은 신분이나 지위에 따르는 도덕적 책임과 의무', t: '가진 자의 책임' },
    { a: '톨레랑스', d: 'h', b: 'tolérance=프랑스어로 관용', m: '나와 다른 생각이나 행동을 존중하고 받아들이는 관용', t: '다름을 인정하는 태도' },
    { a: '르포', d: 'h', b: 'reportage=프랑스어로 보고, 기록', m: '현장을 직접 찾아가 취재하고 쓴 보도 기사', t: '현장 르포' },
    { a: '몽타주', d: 'h', b: 'montage=프랑스어로 조립', m: '따로 찍은 장면들을 이어 붙이는 편집 기법, 또는 여러 얼굴을 합성한 범인 사진', t: '영화 편집 + 수배 전단' },
    { a: '아방가르드', d: 'h', b: 'avant-garde=프랑스어로 군대의 선발대', m: '기존의 틀을 깨는 혁신적이고 실험적인 예술 경향', t: '전위 예술' },
    { a: '프로파간다', d: 'h', b: 'propagare=라틴어로 퍼뜨리다', m: '특정한 생각을 퍼뜨리기 위한 정치적 선전', t: '전쟁 포스터' },
    { a: '데카당스', d: 'h', b: 'décadence=프랑스어로 쇠퇴', m: '19세기 말 유행한 퇴폐적이고 탐미적인 예술 경향', t: '아름답지만 병든 분위기' },

    // ── 콩글리시 → 영어 ──
    { q: KONGLISH('사인(유명인의 서명)'), a: 'autograph', w: ['sign', 'signal', 'mark'], d: 'e', m: "유명인에게 받는 사인은 autograph, 서류에 하는 서명은 signature예요. sign은 주로 '서명하다'라는 동사로 써요.", t: '"Can I get your autograph?"' },
    { q: KONGLISH('에어컨'), a: 'air conditioner', w: ['air control', 'air cooler', 'aircon machine'], d: 'e', m: '정식 명칭은 air conditioner이고, 미국에서는 줄여서 AC라고도 해요.', t: '에어컨 = AC' },
    { q: KONGLISH('리모컨'), a: 'remote', w: ['remocon', 'controller box', 'channel stick'], d: 'e', m: 'remote control을 줄여 보통 remote라고 해요.', t: '"Where\'s the remote?"' },
    { q: KONGLISH('콘센트'), a: 'outlet', w: ['consent', 'plug hole', 'power hole'], d: 'e', m: '미국에서는 outlet, 영국에서는 socket이라고 해요. consent는 \'동의\'라는 뜻이에요.', t: '콘센트(consent) = 동의, 전기 구멍 = outlet' },
    { q: KONGLISH('핸들(자동차)'), a: 'steering wheel', w: ['handle', 'car wheel', 'driving bar'], d: 'e', m: '자동차 운전대는 steering wheel이에요. handle은 문손잡이 같은 손잡이예요.', t: 'steer = 방향을 조종하다' },
    { q: KONGLISH('오토바이'), a: 'motorcycle', w: ['auto bike', 'autobi', 'motor car'], d: 'e', m: "'오토바이'는 auto와 bicycle을 합친 일본식 영어예요. 영어로는 motorcycle 또는 motorbike예요.", t: '일본에서 건너온 말' },
    { q: KONGLISH('원룸'), a: 'studio apartment', w: ['one room', 'single house', 'solo room'], d: 'n', m: '방 하나에 주방과 욕실이 함께 있는 집은 studio (apartment)라고 해요.', t: 'one room이라고 하면 그냥 \'방 하나\'' },
    { q: KONGLISH('개그맨'), a: 'comedian', w: ['gagman', 'funny man', 'joker star'], d: 'e', m: '웃기는 사람을 직업으로 하는 사람은 comedian이에요. gag는 \'농담, 개그\'라는 뜻은 있지만 gagman은 거의 안 써요.', t: '스탠드업 코미디언' },
    { q: KONGLISH('탤런트(드라마 배우)'), a: 'TV actor', w: ['talent', 'drama man', 'star player'], d: 'n', m: 'talent는 \'재능\'이나 \'재능 있는 사람\'이라는 뜻이에요. 드라마 배우는 TV actor 또는 actress라고 해요.', t: 'talent = 재능' },
    { q: KONGLISH('서비스(공짜로 더 주는 것)'), a: "It's on the house", w: ["It's service", 'Free service time', 'Service gift'], d: 'n', m: "가게에서 공짜로 주는 건 \"It's on the house\"(가게가 낸다)라고 해요. service는 '접객, 응대'라는 뜻이에요.", t: '가게(house)가 계산함' },
    { q: KONGLISH('더치페이'), a: 'split the bill', w: ['Dutch pay', 'each pay', 'pay half'], d: 'n', m: "각자 계산하는 건 split the bill 또는 go Dutch라고 해요. 'Dutch pay'는 콩글리시예요.", t: '"Let\'s split the bill"' },
    { q: KONGLISH('커닝(시험 부정행위)'), a: 'cheating', w: ['cunning', 'peeking test', 'copy test'], d: 'e', m: "시험 부정행위는 cheating이에요. cunning은 '교활한'이라는 형용사예요.", t: 'cunning = 교활한' },
    { q: KONGLISH('샤프(펜슬)'), a: 'mechanical pencil', w: ['sharp pencil', 'sharp pen', 'auto pencil'], d: 'n', m: "샤프는 일본 회사 Sharp의 이름에서 온 말이에요. 영어로는 mechanical pencil이라고 해요.", t: '기계식 연필' },
    { q: KONGLISH('호치키스'), a: 'stapler', w: ['hotchkiss', 'paper pin', 'clipper'], d: 'n', m: "'호치키스'는 이 물건을 만든 회사 이름에서 왔어요. 영어로는 stapler예요.", t: '심(staple)을 박는 기계' },
    { q: KONGLISH('매직(펜)'), a: 'marker', w: ['magic pen', 'magic stick', 'color pen'], d: 'n', m: "'매직'은 Magic Marker라는 상품 이름에서 왔어요. 영어로는 marker라고 해요.", t: '상표 이름이 물건 이름이 된 경우' },
    { q: KONGLISH('비닐봉지'), a: 'plastic bag', w: ['vinyl bag', 'vinyl pack', 'nylon bag'], d: 'n', m: '마트 봉지는 plastic bag이에요. vinyl은 레코드판이나 비닐 소재를 말할 때 써요.', t: 'vinyl = LP판' },
    { q: KONGLISH('츄리닝'), a: 'sweatsuit', w: ['training wear', 'trainer suit', 'gym wear'], d: 'n', m: "'츄리닝'은 training이 일본을 거치며 바뀐 말이에요. 영어로는 sweatsuit나 tracksuit라고 해요.", t: '땀(sweat) 흘릴 때 입는 옷' },
    { q: KONGLISH('와이셔츠'), a: 'dress shirt', w: ['Y-shirt', 'white shirt', 'office shirt'], d: 'n', m: "'와이셔츠'는 white shirt가 일본에서 변한 말이에요. 정장용 셔츠는 dress shirt라고 해요.", t: 'Y가 아니라 white에서' },
    { q: KONGLISH('패딩(점퍼)'), a: 'puffer jacket', w: ['padding', 'padding jumper', 'cotton coat'], d: 'n', m: "padding은 '속에 넣는 충전재'라는 뜻이에요. 부풀어 오른 겨울 점퍼는 puffer jacket 또는 down jacket이에요.", t: 'puff = 부풀다' },
    { q: KONGLISH('맨투맨(티셔츠)'), a: 'sweatshirt', w: ['man to man', 'one to one shirt', 'round tee'], d: 'n', m: "목이 둥근 긴소매 면 티셔츠는 sweatshirt예요. man-to-man은 '일대일'이라는 뜻이에요.", t: '맨투맨 = 1:1 수비' },
    { q: KONGLISH('후드티'), a: 'hoodie', w: ['hood tee', 'hood T-shirt', 'cap shirt'], d: 'e', m: '모자(hood)가 달린 티셔츠는 hoodie예요.', t: 'hood + ie' },
    { q: KONGLISH('스킨(화장품)'), a: 'toner', w: ['skin', 'skin water', 'face lotion'], d: 'n', m: "세안 후 바르는 '스킨'은 영어로 toner예요. skin은 그냥 '피부'예요.", t: '"I need skin" = 피부가 필요해(?)' },
    { q: KONGLISH('체크카드'), a: 'debit card', w: ['check card', 'cash card', 'bank pass'], d: 'n', m: '통장에서 바로 돈이 빠져나가는 카드는 debit card예요.', t: 'debit = 차변, 출금' },
    { q: KONGLISH('헬스(장)'), a: 'gym', w: ['health', 'health club room', 'fitness hall'], d: 'e', m: "운동하러 가는 곳은 gym이에요. \"I'm going to health\"는 어색한 표현이에요.", t: '"I\'m going to the gym"' },
    { q: KONGLISH('모닝콜'), a: 'wake-up call', w: ['morning call', 'alarm talk', 'sunrise call'], d: 'n', m: '호텔에서 깨워 주는 전화는 wake-up call이에요.', t: '깨우는(wake up) 전화' },
    { q: KONGLISH('스펙(취업 조건)'), a: 'qualifications', w: ['spec', 'specials', 'skill list'], d: 'h', m: "spec은 specification(제품 사양)의 줄임말이에요. 사람의 자격과 경력은 qualifications라고 해요.", t: '사람에겐 사양(spec)이 아니라 자격' },
    { q: KONGLISH('오바이트(구토)'), a: 'throw up', w: ['overeat', 'over bite', 'eat over'], d: 'h', m: "'오바이트'는 overeat(과식하다)에서 잘못 퍼진 말이에요. 토하다는 throw up 또는 vomit이에요.", t: 'overeat = 과식 ≠ 구토' },
    { q: KONGLISH('사이다(탄산음료)'), a: 'lemon-lime soda', w: ['cider', 'soda cider', 'sweet cider'], d: 'h', m: "영어 cider는 사과즙이나 사과로 만든 술이에요. 우리가 마시는 투명한 탄산음료는 lemon-lime soda예요.", t: '미국에서 cider 시키면 사과 주스' },
    { q: KONGLISH('레포트(과제물)'), a: 'paper', w: ['report homework', 'study report', 'class report'], d: 'h', m: "대학 과제로 내는 글은 보통 paper나 essay라고 해요. report는 조사·보고서에 가까워요.", t: '"I have a paper due tomorrow"' },
    { q: KONGLISH('미팅(단체 소개팅)'), a: 'group blind date', w: ['meeting', 'group meeting', 'love meeting'], d: 'h', m: "영어 meeting은 회의예요. 여러 명이 함께하는 소개팅은 group blind date라고 해요.", t: 'meeting = 회의' },
    { q: KONGLISH('스탠드(책상 조명)'), a: 'desk lamp', w: ['stand', 'light stand', 'table stand'], d: 'h', m: "책상 위 조명은 desk lamp예요. stand는 '받침대'라는 뜻이에요.", t: 'lamp가 핵심' },
    { q: KONGLISH('깁스'), a: 'cast', w: ['gips', 'bone wrap', 'arm guard'], d: 'h', m: "부러진 뼈를 고정하는 석고 붕대는 영어로 cast예요. '깁스'는 석고를 뜻하는 독일어 Gips에서 왔어요.", t: '"I have a cast on my arm"' },
    { q: KONGLISH('포클레인'), a: 'excavator', w: ['poclain', 'digging car', 'crane truck'], d: 'h', m: "'포클레인'은 프랑스 건설 장비 회사 Poclain의 이름이에요. 땅 파는 중장비는 excavator예요.", t: '회사 이름이 장비 이름이 된 경우' },

    // ── 어원 ──
    { q: ORIGIN('담배'), a: '포르투갈어', w: ['영어', '중국어', '네덜란드어'], d: 'n', m: '포르투갈어 tabaco가 일본을 거쳐 들어와 담배가 되었어요.', t: '포르투갈 상인들이 퍼뜨린 말 (빵과 같은 경로)' },
    { q: ORIGIN('카스텔라'), a: '포르투갈어', w: ['스페인어', '이탈리아어', '프랑스어'], d: 'h', m: "스페인의 카스티야 지방 빵이라는 뜻의 포르투갈어 '판 데 카스텔라(Pão de Castela)'가 일본에 전해지며 이름이 되었어요.", t: '카스티야(Castilla)의 빵' },
    { q: ORIGIN('망토'), a: '프랑스어', w: ['독일어', '러시아어', '이탈리아어'], d: 'n', m: '프랑스어 manteau(외투)에서 왔어요.', t: '망토 = manteau' },
    { q: ORIGIN('템포'), a: '이탈리아어', w: ['프랑스어', '독일어', '영어'], d: 'n', m: "이탈리아어로 '시간'이라는 뜻이에요. 음악 용어는 이탈리아어가 많아요.", t: '피아노, 오페라, 템포 = 이탈리아어' },
    { q: ORIGIN('요구르트'), a: '튀르키예어', w: ['그리스어', '불가리아어', '러시아어'], d: 'h', m: "튀르키예어 yoğurt(걸쭉하게 하다)에서 왔어요.", t: '유목민의 발효유' },
    { q: ORIGIN('로봇'), a: '체코어', w: ['독일어', '영어', '러시아어'], d: 'h', m: "체코 작가 카렐 차페크의 희곡 「R.U.R.」(1920)에서 처음 쓰였어요. '강제 노동'을 뜻하는 체코어 robota에서 만든 말이에요.", t: '로봇의 원래 뜻 = 일꾼' },
    { q: ORIGIN('쓰나미'), a: '일본어', w: ['인도네시아어', '하와이어', '중국어'], d: 'n', m: "일본어로 '항구(津)의 파도(波)'라는 뜻이에요. 지금은 국제적으로 지진 해일을 뜻하는 말이 되었어요.", t: '津(나루 진) + 波(물결 파)' },
    { q: ORIGIN('알코올'), a: '아랍어', w: ['라틴어', '그리스어', '페르시아어'], d: 'h', m: "아랍어 al-kuhl에서 왔어요. 원래는 눈 화장에 쓰던 고운 가루를 뜻했어요.", t: 'al-로 시작하는 말은 아랍어 출신이 많아요 (알고리즘, 알칼리)' },
    { q: ORIGIN('커피'), a: '아랍어', w: ['에티오피아어', '포르투갈어', '스페인어'], d: 'h', m: "아랍어 qahwa가 튀르키예어 kahve를 거쳐 유럽으로 퍼졌어요.", t: '카흐와 → 카흐베 → coffee' },
    { q: ORIGIN('샴푸'), a: '힌디어', w: ['프랑스어', '영어', '이탈리아어'], d: 'h', m: "힌디어 champo(누르다, 마사지하다)에서 왔어요. 영국이 인도를 지배하던 시절 영어로 들어갔어요.", t: '머리 마사지 = 샴푸' },
    { q: ORIGIN('파자마'), a: '힌디어', w: ['프랑스어', '스페인어', '영어'], d: 'h', m: "'다리(pay)에 입는 옷(jama)'이라는 뜻의 페르시아·힌디어에서 영어로 들어갔어요.", t: '원래는 헐렁한 바지' },
    { q: ORIGIN('정글'), a: '힌디어', w: ['포르투갈어', '말레이어', '스와힐리어'], d: 'h', m: "힌디어 jangal(황무지, 숲)에서 왔어요.", t: '『정글북』의 무대도 인도' },
    { q: ORIGIN('아바타'), a: '산스크리트어', w: ['그리스어', '라틴어', '히브리어'], d: 'h', m: "산스크리트어 avatāra(신이 사람이나 동물의 모습으로 내려옴)에서 왔어요. 지금은 가상 세계 속 나의 분신이라는 뜻으로 써요.", t: '신의 화신 → 나의 분신' },
    { q: ORIGIN('가라오케'), a: '일본어', w: ['중국어', '영어', '한국어'], d: 'n', m: "일본어 '가라(空, 비어 있는) + 오케(오케스트라)'로, 반주만 있고 노래는 비어 있다는 뜻이에요.", t: '빈 오케스트라' },
    { q: ORIGIN('구두'), a: '일본어', w: ['네덜란드어', '프랑스어', '영어'], d: 'h', m: "일본어 '구쓰(くつ, 신발)'에서 온 말로 알려져 있어요.", t: '일본어에서 온 생활어' },
    { q: ORIGIN('케첩'), a: '중국 남부 방언', w: ['영어', '스페인어', '아즈텍어'], d: 'h', m: "중국 남부 민난어의 '케찹(생선을 절인 소스)'에서 왔다는 설이 유력해요. 처음엔 토마토가 아니라 생선 소스였어요.", t: '처음 케첩은 생선 젓갈 소스' },
    { q: ORIGIN('피아노'), a: '이탈리아어', w: ['독일어', '오스트리아어', '프랑스어'], d: 'n', m: "이탈리아어 pianoforte(여리게-세게)를 줄인 말이에요. 건반을 누르는 세기로 소리 크기를 조절할 수 있어 붙은 이름이에요.", t: 'piano(여리게) + forte(세게)' },
  ],
}
