const KONGLISH = (k) => `한국에서 쓰는 '${k}'에 해당하는 자연스러운 영어 표현은?`
const eun = (w) => ((w.slice(-1).charCodeAt(0) - 0xac00) % 28 ? '은' : '는')
const ORIGIN = (w) => `'${w}'${eun(w)} 어느 나라 말에서 왔을까?`

export default {
  category: 'loanword',
  name: 'm4',
  label: '외래어',
  cards: [
    // ── 콩글리시 ──
    { q: KONGLISH('매니큐어(손톱에 바르는 칠)'), a: 'nail polish', w: ['manicure', 'nail paint cream', 'finger color'], d: 'n', m: '영어 manicure는 손톱을 손질하는 일 전체를 뜻해요.', t: '칠하는 건 polish' },
    { q: KONGLISH('볼펜'), a: 'ballpoint pen', w: ['ball pen stick', 'oil pen', 'round pen'], d: 'e', m: '줄여서 그냥 pen이라고도 해요.', t: 'ballpoint' },
    { q: KONGLISH('셀카봉'), a: 'selfie stick', w: ['self camera bar', 'selca rod', 'photo pole'], d: 'e', m: '셀카는 영어로 selfie예요.', t: 'selfie + stick' },
    { q: KONGLISH('원피스(위아래가 붙은 옷)'), a: 'dress', w: ['one-piece', 'one suit', 'full skirt'], d: 'n', m: '영어 one-piece는 주로 위아래가 붙은 수영복을 떠올려요.', t: '원피스 = dress' },
    { q: KONGLISH('가스레인지'), a: 'stove', w: ['gas range set', 'gas fire', 'cooking range gas'], d: 'n', m: '미국에서는 stove, 영국에서는 cooker나 hob이라고도 해요.', t: '불 쓰는 조리대' },
    { q: KONGLISH('클랙슨(자동차 경적)'), a: 'horn', w: ['klaxon bell', 'car bell', 'beeper'], d: 'n', m: 'klaxon은 옛 경적 회사 이름에서 왔어요. "경적을 울리다"는 honk the horn이에요.', t: '빵빵 = horn' },
    { q: KONGLISH('엑셀(자동차 가속 페달)'), a: 'gas pedal', w: ['excel', 'speed foot', 'go button'], d: 'n', m: '정식 이름은 accelerator예요. 엑셀은 이것을 줄인 말이에요.', t: 'accelerator' },
    { q: KONGLISH('본네트(자동차 앞쪽 덮개)'), a: 'hood', w: ['bonnet car', 'front cap', 'engine roof'], d: 'h', m: '미국은 hood, 영국은 bonnet이라고 해요. 본네트는 영국식에서 왔어요.', t: '미국 hood, 영국 bonnet' },
    { q: KONGLISH('카센터'), a: 'auto repair shop', w: ['car center', 'car hospital', 'motor service center room'], d: 'n', m: 'car center라고 하면 자동차 판매장처럼 들릴 수 있어요.', t: '정비소' },
    { q: KONGLISH('펜션(숙박 시설)'), a: 'guesthouse', w: ['pension', 'rest hotel', 'villa house'], d: 'h', m: '영어 pension은 주로 \'연금\'이라는 뜻이에요.', t: 'pension = 연금' },
    { q: KONGLISH('플래카드(현수막)'), a: 'banner', w: ['placard', 'hanging paper', 'cloth sign board'], d: 'h', m: 'placard는 손에 들고 다니는 피켓 같은 판을 말해요.', t: '현수막 = banner' },
    { q: KONGLISH('포스트잇'), a: 'sticky note', w: ['post paper', 'memo glue', 'stick memo'], d: 'n', m: 'Post-it은 3M의 상표 이름이라 일반적으로는 sticky note라고 해요.', t: '붙이는 메모지' },
    { q: KONGLISH('화이트(수정액)'), a: 'correction fluid', w: ['white', 'erase water', 'clean ink'], d: 'n', m: '미국에서는 상표 이름을 딴 White-Out이라는 말도 많이 써요.', t: '고치는 액체' },
    { q: KONGLISH('커트라인(합격선)'), a: 'cutoff score', w: ['cut line', 'pass line point', 'border cut'], d: 'n', m: '"cutoff"는 \'기준선\'이라는 뜻이에요.', t: 'cutoff' },
    { q: KONGLISH('런닝셔츠(민소매 속옷)'), a: 'undershirt', w: ['running shirt', 'sleeveless run', 'sports top'], d: 'n', m: '영어 running shirt는 달리기할 때 입는 운동복을 말해요. 민소매 겉옷은 tank top이에요.', t: '속옷 = undershirt' },
    { q: KONGLISH('백댄서'), a: 'backup dancer', w: ['back dancer', 'behind dancer', 'sub dancer'], d: 'e', m: 'backup은 \'뒤에서 받쳐 주는\'이라는 뜻이에요. 백 코러스도 backup singer예요.', t: 'backup' },
    { q: KONGLISH('노래방'), a: 'karaoke room', w: ['song room', 'singing bang', 'music cafe'], d: 'e', m: 'karaoke는 일본어 \'가라(빈) + 오케(오케스트라)\'에서 온 말이에요.', t: '빈 오케스트라' },
    { q: KONGLISH('피시방'), a: 'internet cafe', w: ['PC room', 'computer bang', 'game house'], d: 'n', m: '요즘은 gaming cafe라고도 해요. PC bang이라는 말이 외국에 알려지기도 했어요.', t: '인터넷 카페' },
    { q: KONGLISH('개런티(출연료)'), a: 'appearance fee', w: ['guarantee', 'show money', 'pay guarantee'], d: 'h', m: '영어 guarantee는 \'보증\'이라는 뜻이에요.', t: 'guarantee = 보증' },
    { q: KONGLISH('레미콘'), a: 'concrete mixer truck', w: ['remicon', 'cement car', 'mix truck stone'], d: 'h', m: '레미콘은 ready-mixed concrete(미리 섞은 콘크리트)를 줄인 일본식 말이에요.', t: 'ready-mixed concrete' },

    // ── 어디서 온 말일까 ──
    { q: ORIGIN('앙케트'), a: '프랑스어', w: ['독일어', '러시아어', '영어'], d: 'n', m: '프랑스어 enquête(조사)에서 왔어요. 영어로는 survey예요.', t: '설문 조사' },
    { q: ORIGIN('깁스'), a: '독일어', w: ['영어', '라틴어', '네덜란드어'], d: 'n', m: '독일어 Gips(석고)에서 왔어요. 영어로는 cast라고 해요.', t: 'Gips = 석고' },
    { q: ORIGIN('랜드마크'), a: '영어', w: ['독일어', '프랑스어', '네덜란드어'], d: 'e', m: '원래 탐험가가 길을 찾으려고 표시해 둔 \'땅(land)의 표시(mark)\'라는 뜻이에요.', t: 'land + mark' },
    { q: ORIGIN('부케'), a: '프랑스어', w: ['영어', '이탈리아어', '스페인어'], d: 'n', m: '\'꽃다발\'이라는 뜻이에요. 결혼식에서 신부가 들어요.', t: 'bouquet' },
    { q: ORIGIN('비엔날레'), a: '이탈리아어', w: ['프랑스어', '라틴어', '스페인어'], d: 'h', m: '\'2년마다\'라는 뜻이에요. 3년마다 열리면 트리엔날레예요.', t: '2년마다' },

    // ── 외래어 뜻 ──
    { a: '레전드', d: 'e', b: 'legend=전설', m: '한 분야에서 오래도록 기억될 만큼 뛰어난 사람이나 일', t: '"그 경기는 레전드다"' },
    { a: '로드맵', d: 'n', b: 'road=길 / map=지도', m: '앞으로 할 일의 목표와 단계를 시간 순서대로 정리한 계획', t: '계획표' },
    { a: '루머', d: 'e', b: 'rumor=소문', m: '근거 없이 퍼진 소문', t: '뜬소문' },
    { a: '리더십', d: 'e', b: 'leader=이끄는 사람 / ship=자질', m: '무리를 이끌어 가는 지도자의 능력', t: '지도력' },
    { a: '메커니즘', d: 'n', m: '어떤 일이 이뤄지는 원리나 짜임새', t: '작동 원리' },
    { a: '모멘텀', d: 'h', b: 'momentum=움직이는 힘', m: '어떤 흐름이 계속 이어지게 하는 추진력이나 계기', t: '상승세의 탄력' },
    { a: '빈티지', d: 'n', m: '오래되었지만 멋과 가치가 있는 물건이나 그런 스타일', t: '중고 옷 가게의 멋' },
    { a: '솔루션', d: 'n', b: 'solution=해결', m: '문제를 해결하는 방법이나 그 수단', t: '해결책' },
    { a: '스토리텔링', d: 'n', b: 'story=이야기 / telling=들려주기', m: '전하려는 내용을 재미있는 이야기로 풀어 전달하는 것', t: '이야기로 전달하기' },
    { a: '아날로그', d: 'n', m: '숫자 대신 연속된 양으로 나타내는 방식, 또는 손맛과 옛 감성이 느껴지는 것', t: 'LP판, 필름 카메라' },
    { a: '알리바이', d: 'n', b: 'alibi=라틴어로 \'다른 곳에\'', m: '범죄가 일어난 때 다른 곳에 있었다는 증명', t: '현장 부재 증명' },
    { a: '애드리브', d: 'n', b: 'ad libitum=라틴어로 \'마음대로\'', m: '대본에 없는 말이나 연기를 즉흥적으로 하는 것', t: '즉흥 대사' },
    { a: '어드밴티지', d: 'n', b: 'advantage=유리함', m: '다른 쪽보다 앞서거나 유리한 조건', t: '홈 어드밴티지' },
    { a: '엘리트', d: 'e', m: '사회나 집단에서 뛰어난 능력을 인정받은 사람', t: '최고 인재' },
    { a: '옵션', d: 'e', b: 'option=선택', m: '기본에 더해 따로 고를 수 있는 사항', t: '"풀옵션 원룸"' },
    { a: '이노베이션', d: 'n', b: 'innovation=혁신', m: '낡은 방식을 바꿔 새롭게 하는 것', t: '혁신' },
    { a: '이데올로기', d: 'h', m: '사회나 집단이 가진 생각과 가치의 체계', t: '이념' },
    { a: '제스처', d: 'e', b: 'gesture=몸짓', m: '말을 하면서 뜻을 더 잘 전하려고 쓰는 손짓이나 몸짓', t: '손짓 몸짓' },
    { a: '챌린지', d: 'e', b: 'challenge=도전', m: '여러 사람이 같은 행동을 따라 하며 영상 등을 올리는 놀이식 도전', t: '춤 챌린지' },
    { a: '콘텐츠', d: 'e', b: 'contents=내용물', m: '인터넷이나 방송으로 제공되는 글, 영상, 음악 같은 정보와 창작물', t: '유튜브 영상' },
    { a: '쿼터', d: 'h', b: 'quota=할당량', m: '정해진 몫이나 할당된 양', t: '스크린 쿼터' },
    { a: '터닝 포인트', d: 'n', b: 'turning=돌아서는 / point=지점', m: '상황이나 흐름이 크게 바뀌는 계기나 시점', t: '전환점' },
    { a: '텐션', d: 'n', b: 'tension=팽팽함', m: '분위기나 기분이 들뜨고 활기찬 정도', t: '"텐션 높다"' },
    { a: '템플릿', d: 'n', m: '문서나 디자인을 쉽게 만들도록 미리 짜 놓은 틀', t: 'PPT 서식' },
    { a: '트리거', d: 'h', b: 'trigger=방아쇠', m: '어떤 일이나 반응을 일으키는 계기', t: '방아쇠 역할' },
    { a: '팩트', d: 'e', b: 'fact=사실', m: '실제로 있었던 일이나 확인된 사실', t: '"팩트 체크"' },
    { a: '포비아', d: 'n', b: 'phobia=그리스어로 \'두려움\'', m: '특정한 대상이나 상황에 대한 지나친 공포', t: '공포증' },
    { a: '퓨전', d: 'n', b: 'fusion=융합', m: '서로 다른 문화나 장르를 섞어 새롭게 만든 것', t: '퓨전 한식' },
    { a: '하이라이트', d: 'e', b: 'high=높은 / light=빛', m: '가장 중요하거나 흥미로운 장면이나 부분', t: '경기 요약 영상' },
    { a: '헤리티지', d: 'h', b: 'heritage=유산', m: '오래 이어져 온 전통이나 유산, 또는 브랜드가 쌓아 온 역사', t: '물려받은 전통' },
  ],
}
