// 어근: 단어의 중심 뜻을 담은 조각 (대부분 라틴어·그리스어에서 왔어요)
export default {
  cards: [
    { r: 'dict', d: 'e', m: '말하다', from: '라틴어 dicere', ex: 'predict · dictionary · contradict', t: '딕셔너리(dictionary)는 말을 모아 둔 책.' },
    { r: 'spect', d: 'e', m: '보다', from: '라틴어 specere', ex: 'inspect · respect · spectator', t: '스펙터클(spectacle)은 볼거리.', syn: ['vis', 'scope'] },
    { r: 'port', d: 'e', m: '나르다', from: '라틴어 portare', ex: 'import · export · portable', t: '포터(porter)는 짐 나르는 사람.', syn: ['fer'] },
    { r: 'duct', d: 'n', m: '이끌다', from: '라틴어 ducere', ex: 'conduct · produce · educate', t: '덕트(duct)는 공기를 이끄는 관. duc(e)로도 써요.' },
    { r: 'mit', d: 'n', m: '보내다', from: '라틴어 mittere', ex: 'submit · transmit · mission', t: 'miss로도 바뀌어요. 미션(mission)은 보내서 맡긴 일.' },
    { r: 'ject', d: 'n', m: '던지다', from: '라틴어 iacere', ex: 'project · reject · inject', t: '프로젝터는 빛을 앞으로 던지는 기계.' },
    { r: 'tract', d: 'n', m: '끌다', from: '라틴어 trahere', ex: 'attract · tractor · distract', t: '트랙터(tractor)는 끄는 차.' },
    { r: 'struct', d: 'n', m: '세우다, 쌓다', from: '라틴어 struere', ex: 'structure · construct · destroy', t: '스트럭처(structure)는 쌓아 세운 구조.' },
    { r: 'vert', d: 'n', m: '돌리다', from: '라틴어 vertere', ex: 'convert · reverse · version', t: 'vers로도 써요. 버전(version)은 방향을 돌려 바꾼 것.' },
    { r: 'ven', d: 'n', m: '오다', from: '라틴어 venire', ex: 'event · prevent · convention', t: '이벤트(event)는 밖으로 나온(e-) 일. vent로도 써요.' },
    { r: 'cede', d: 'h', m: '가다, 물러나다', from: '라틴어 cedere', ex: 'proceed · precede · access', t: 'ceed·cess로도 바뀌어요. 액세스(access)는 다가가는 것.', syn: ['migr', 'cur'] },
    { r: 'press', d: 'e', m: '누르다', from: '라틴어 premere', ex: 'pressure · express · depress', t: '프레스기는 누르는 기계.' },
    { r: 'fer', d: 'n', m: '나르다, 옮기다', from: '라틴어 ferre', ex: 'transfer · offer · prefer', t: '트랜스퍼(transfer)는 건너서(trans) 옮겨 타는 환승.', syn: ['port'] },
    { r: 'form', d: 'e', m: '모양', from: '라틴어 forma', ex: 'reform · uniform · transform', t: '폼(form) 잡다 = 모양을 갖추다.' },
    { r: 'rupt', d: 'n', m: '깨다, 터지다', from: '라틴어 rumpere', ex: 'erupt · interrupt · bankrupt', t: '화산이 이럽트(erupt)하면 밖으로 터져 나와요.' },
    { r: 'scrib', d: 'n', m: '쓰다', from: '라틴어 scribere', ex: 'describe · subscribe · script', t: 'script로도 바뀌어요. 스크립트(script)는 써 둔 대본.', syn: ['graph'] },
    { r: 'graph', d: 'e', m: '쓰다, 그리다', from: '그리스어 graphein', ex: 'autograph · photograph · paragraph', t: '그래프는 그린 것.', syn: ['scrib'] },
    { r: 'log', d: 'n', m: '말, 학문', from: '그리스어 logos', ex: 'dialogue · logic · biology', t: '-logy가 붙으면 학문 이름(biology 생물학)이 돼요.' },
    { r: 'phon', d: 'e', m: '소리', from: '그리스어 phone', ex: 'telephone · symphony · microphone', t: '폰(phone)은 소리를 전하는 기계.', syn: ['son', 'aud'] },
    { r: 'vis', d: 'e', m: '보다', from: '라틴어 videre', ex: 'vision · visible · revise', t: 'vid로도 써요. 비디오(video)도 같은 뿌리.', syn: ['spect', 'scope'] },
    { r: 'aud', d: 'e', m: '듣다', from: '라틴어 audire', ex: 'audio · audience · audition', t: '오디오(audio)는 듣는 장치.', syn: ['phon', 'son'] },
    { r: 'cred', d: 'n', m: '믿다', from: '라틴어 credere', ex: 'credit · incredible · credible', t: '크레딧카드는 믿고 먼저 쓰게 해 주는 카드.', syn: ['fid'] },
    { r: 'fid', d: 'h', m: '믿다, 충실하다', from: '라틴어 fidere', ex: 'confident · confide · fidelity', t: '하이파이(hi-fi)의 fi는 fidelity, 원음에 충실함.', syn: ['cred'] },
    { r: 'mov', d: 'e', m: '움직이다', from: '라틴어 movere', ex: 'remove · motion · promote', t: 'mot로도 바뀌어요. 무비(movie)는 움직이는 그림.' },
    { r: 'pend', d: 'n', m: '매달다, 무게를 달다', from: '라틴어 pendere', ex: 'depend · suspend · pendant', t: '펜던트(pendant)는 목에 매다는 장식. pens로도 써요(expensive).' },
    { r: 'pos', d: 'n', m: '놓다, 두다', from: '라틴어 ponere', ex: 'position · propose · expose', t: 'pon으로도 써요(postpone). 포지션은 놓인 자리.' },
    { r: 'sta', d: 'n', m: '서다', from: '라틴어 stare', ex: 'stable · status · obstacle', t: 'stat·stit·sist로도 바뀌어요. 스탠드(stand)도 같은 계열.' },
    { r: 'tain', d: 'n', m: '잡다, 쥐다', from: '라틴어 tenere', ex: 'contain · obtain · maintain', t: 'ten으로도 써요(tenant 세입자).', syn: ['cap'] },
    { r: 'voc', d: 'n', m: '목소리, 부르다', from: '라틴어 vocare', ex: 'vocal · advocate · provoke', t: '보컬(vocal)은 목소리 담당. vok로도 써요.' },
    { r: 'cap', d: 'n', m: '잡다, 받아들이다', from: '라틴어 capere', ex: 'capture · capable · accept', t: 'cept·ceive로도 바뀌어요. 캡처(capture)는 화면을 잡는 것.', syn: ['tain'] },
    { r: 'sent', d: 'n', m: '느끼다', from: '라틴어 sentire', ex: 'sense · consent · sensitive', t: 'sens로도 써요. 센스 있다 = 잘 느낀다.' },
    { r: 'sequ', d: 'h', m: '뒤따르다', from: '라틴어 sequi', ex: 'sequence · consequence · subsequent', t: '시퀀스(sequence)는 뒤따라 이어지는 순서. secu로도 써요.' },
    { r: 'solv', d: 'n', m: '풀다', from: '라틴어 solvere', ex: 'solve · dissolve · resolve', t: '솔루션(solution)은 문제를 푼 답.' },
    { r: 'spir', d: 'n', m: '숨 쉬다', from: '라틴어 spirare', ex: 'inspire · spirit · expire', t: '스피릿(spirit)은 숨결, 정신.' },
    { r: 'tend', d: 'n', m: '뻗다', from: '라틴어 tendere', ex: 'extend · attend · tension', t: 'tens로도 써요. 텐션(tension)은 팽팽하게 뻗은 상태.' },
    { r: 'vac', d: 'n', m: '비어 있는', from: '라틴어 vacare', ex: 'vacant · vacation · vacuum', t: '배케이션(vacation)은 일정을 비우는 휴가.' },
    { r: 'val', d: 'n', m: '가치, 힘', from: '라틴어 valere', ex: 'value · valid · evaluate', t: '밸류(value)는 가치.' },
    { r: 'viv', d: 'n', m: '살다', from: '라틴어 vivere', ex: 'survive · vivid · revive', t: 'vit로도 써요. 비타민(vitamin)은 살게 하는 영양소.', syn: ['bio'] },
    { r: 'chron', d: 'h', m: '시간', from: '그리스어 chronos', ex: 'chronic · chronicle · synchronize', t: '크로노그래프(chronograph)는 시간을 재는 시계.', syn: ['temp'] },
    { r: 'bio', d: 'e', m: '생명', from: '그리스어 bios', ex: 'biology · biography · antibiotic', t: '바이오(bio) 산업은 생명 산업.', syn: ['viv'] },
    { r: 'geo', d: 'e', m: '땅, 지구', from: '그리스어 ge', ex: 'geography · geology · geometry', t: '지오(geo)는 땅. 지리(geography)는 땅을 그린 것.', syn: ['terr'] },
    { r: 'path', d: 'n', m: '느낌, 고통', from: '그리스어 pathos', ex: 'sympathy · empathy · pathetic', t: '파토스(pathos)는 감정에 호소하는 힘.' },
    { r: 'gen', d: 'n', m: '낳다, 생기다', from: '라틴어·그리스어 gen', ex: 'generate · gene · genius', t: '진(gene)은 생명을 낳는 유전자.' },
    { r: 'cid', d: 'h', m: '자르다, 죽이다', from: '라틴어 caedere', ex: 'decide · suicide · pesticide', t: 'cis로도 써요(precise). 결정(decide)은 다른 길을 잘라 내는 것.', syn: ['sect'] },
    { r: 'fac', d: 'n', m: '만들다, 하다', from: '라틴어 facere', ex: 'factory · effect · affect', t: 'fect·fic로도 바뀌어요. 팩토리(factory)는 만드는 곳.' },
    { r: 'fin', d: 'e', m: '끝, 경계', from: '라틴어 finis', ex: 'final · finish · infinite', t: '피날레(finale)는 끝 장면.' },
    { r: 'flu', d: 'n', m: '흐르다', from: '라틴어 fluere', ex: 'fluid · influence · fluent', t: '플루이드(fluid)는 흐르는 것, 유체.' },
    { r: 'grad', d: 'n', m: '걸음, 단계', from: '라틴어 gradus', ex: 'grade · gradual · progress', t: 'gress로도 바뀌어요. 그레이드(grade)는 한 단계.' },
    { r: 'junct', d: 'h', m: '잇다', from: '라틴어 iungere', ex: 'junction · conjunction · joint', t: '정션(junction)은 길이 이어지는 교차점.' },
    { r: 'loc', d: 'e', m: '장소', from: '라틴어 locus', ex: 'local · location · allocate', t: '로컬(local)은 그 장소의.' },
    { r: 'man', d: 'n', m: '손', from: '라틴어 manus', ex: 'manual · manufacture · manage', t: '매뉴얼(manual)은 손에 들고 보는 안내서.' },
    { r: 'mand', d: 'h', m: '명령하다, 맡기다', from: '라틴어 mandare', ex: 'command · demand · mandatory', t: '커맨드(command)는 명령.' },
    { r: 'med', d: 'n', m: '가운데', from: '라틴어 medius', ex: 'medium · media · mediate', t: '미디엄(medium) 사이즈는 가운데 크기.' },
    { r: 'migr', d: 'n', m: '옮겨 가다', from: '라틴어 migrare', ex: 'migrate · immigrant · emigrate', t: '마이그레이션(migration)은 데이터를 옮기는 일.' },
    { r: 'mort', d: 'n', m: '죽음', from: '라틴어 mors', ex: 'mortal · immortal · mortgage', t: '모기지(mortgage)는 옛 프랑스어로 "죽은 약속". 빚을 다 갚으면 약속이 죽어 끝나요.' },
    { r: 'nov', d: 'n', m: '새로운', from: '라틴어 novus', ex: 'novel · innovate · renovate', t: '노벨(novel)은 새로운 이야기, 소설.' },
    { r: 'ped', d: 'n', m: '발', from: '라틴어 pes', ex: 'pedal · pedestrian · expedition', t: '페달(pedal)은 발로 밟는 장치.' },
    { r: 'pel', d: 'h', m: '밀다, 몰다', from: '라틴어 pellere', ex: 'expel · compel · propel', t: 'puls로도 바뀌어요. 프로펠러는 앞으로 미는 장치.' },
    { r: 'plic', d: 'h', m: '접다, 겹치다', from: '라틴어 plicare', ex: 'complicate · duplicate · apply', t: 'ply·plex로도 써요. 컴플렉스(complex)는 여러 겹 접힌 것.' },
    { r: 'quest', d: 'n', m: '묻다, 찾다', from: '라틴어 quaerere', ex: 'question · request · conquer', t: 'quir·quer로도 바뀌어요. 퀘스트는 찾아 나서는 임무.' },
    { r: 'rect', d: 'n', m: '곧은, 바른', from: '라틴어 regere', ex: 'correct · direct · rectangle', t: '렉탱글(rectangle)은 각이 곧은 사각형.' },
    { r: 'sect', d: 'n', m: '자르다', from: '라틴어 secare', ex: 'section · insect · intersection', t: '섹션(section)은 잘라 나눈 부분.', syn: ['cid'] },
    { r: 'son', d: 'h', m: '소리', from: '라틴어 sonus', ex: 'sonic · resonate · unison', t: '소닉(sonic)은 소리의.', syn: ['phon', 'aud'] },
    { r: 'tact', d: 'h', m: '닿다', from: '라틴어 tangere', ex: 'contact · intact · tangible', t: 'tang로도 써요. 콘택트렌즈는 눈에 닿는 렌즈.' },
    { r: 'temp', d: 'n', m: '시간, 때', from: '라틴어 tempus', ex: 'temporary · contemporary · tempo', t: '템포(tempo)는 시간의 빠르기.', syn: ['chron'] },
    { r: 'terr', d: 'n', m: '땅', from: '라틴어 terra', ex: 'territory · terrain · terrace', t: '테라스(terrace)는 땅을 돋운 자리.', syn: ['geo'] },
    { r: 'scope', d: 'n', m: '보는 기구, 살피다', from: '그리스어 skopein', ex: 'telescope · microscope · scope', t: '스코프(scope)는 살펴보는 범위.', syn: ['spect', 'vis'] },
    { r: 'cur', d: 'n', m: '달리다, 흐르다', from: '라틴어 currere', ex: 'current · occur · excursion', t: '커런트(current)는 흐름. course도 같은 뿌리.' },
    { r: 'corp', d: 'h', m: '몸', from: '라틴어 corpus', ex: 'corporation · corpse · incorporate', t: '코퍼레이션(corporation)은 하나의 몸처럼 뭉친 회사.' },
    { r: 'hydr', d: 'n', m: '물', from: '그리스어 hydor', ex: 'hydrogen · dehydrate · hydrant', t: '하이드로(hydro)는 물. 수소(hydrogen)는 물을 만드는 원소.' },
    { r: 'mem', d: 'e', m: '기억하다', from: '라틴어 memor', ex: 'memory · memorial · remember', t: '메모(memo)는 기억하려고 적는 것.' },
    { r: 'nat', d: 'n', m: '태어나다', from: '라틴어 nasci', ex: 'native · nature · innate', t: '네이티브(native)는 거기서 태어난 사람.' },
    { r: 'norm', d: 'n', m: '기준, 규칙', from: '라틴어 norma', ex: 'normal · enormous · norm', t: '노멀(normal)은 기준에 맞는 것.' },
    { r: 'pop', d: 'e', m: '사람들', from: '라틴어 populus', ex: 'popular · population · populate', t: '팝(pop) 음악은 사람들의 음악.' },
    { r: 'vol', d: 'h', m: '바라다, 뜻', from: '라틴어 velle', ex: 'volunteer · benevolent · voluntary', t: '볼런티어(volunteer)는 스스로 바라서 하는 사람.' },
  ],
}
